#!/bin/sh

case $1 in
	i)
	 wget -q --show-progress --progress=bar:force 2>&1 "https://github.com/hexisXz/bzsh-plugins/blob/main/plugins/$2/install"
	;;

        R)
	 sudo rm -r ~/.config/bzsh/plugins/$2
	;;

	l)
	 ls ~/.config/bzsh/plugins
        ;;

        *)
	 echo "usage: i: install plugins

	 R: remove a plugin

	 l: list plugins"
	;;
esac 	
	 
